/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payment;

/**
 *
 * @author USER
 */
public class PaymentUI extends javax.swing.JFrame {

    /**
     * Creates new form PaymentUI
     */
    public PaymentUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new payment.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        dateShowtime = new javax.swing.JLabel();
        movieName = new javax.swing.JLabel();
        movieGenre = new javax.swing.JLabel();
        runtime = new javax.swing.JLabel();
        theatre = new javax.swing.JLabel();
        sound = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(1162, 327));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/Test_Poster.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        dateShowtime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateShowtime.setText("17 October 2024   |  18:00 (Date Showtime)");

        movieName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        movieName.setText("Look Back (Movie Name)");

        movieGenre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        movieGenre.setText("Action, Drama, Romance (Genre)");

        runtime.setText("60 min (Runtime)");

        theatre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        theatre.setText("Theatre 7 (Theatre)");

        sound.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/sound.png"))); // NOI18N
        sound.setText("ENG");

        subtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/subtitle.png"))); // NOI18N
        subtitle.setText("TH (Sound, Subtitle)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("|");

        seat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment/seat.png"))); // NOI18N
        seat.setText("M7 (Seat)");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateShowtime)
                    .addComponent(movieName)
                    .addComponent(movieGenre)
                    .addComponent(runtime)
                    .addComponent(theatre)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(sound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(subtitle))
                    .addComponent(seat))
                .addContainerGap(642, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(dateShowtime)
                        .addGap(18, 18, 18)
                        .addComponent(movieName)
                        .addGap(18, 18, 18)
                        .addComponent(movieGenre)
                        .addGap(18, 18, 18)
                        .addComponent(runtime)
                        .addGap(18, 18, 18)
                        .addComponent(theatre)
                        .addGap(18, 18, 18)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sound)
                            .addComponent(subtitle)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(seat)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PaymentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateShowtime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel movieGenre;
    private javax.swing.JLabel movieName;
    private payment.RoundedPanel roundedPanel1;
    private javax.swing.JLabel runtime;
    private javax.swing.JLabel seat;
    private javax.swing.JLabel sound;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel theatre;
    // End of variables declaration//GEN-END:variables
}
